import {useEffect,useState} from 'react';
import type {Dispatch,SetStateAction} from 'react';
import type {ResolvedVideoConfig,VideoTextLayer} from '../types/video';

type UpdateStatus={running:boolean;log:string;version:string};
type Props={config:ResolvedVideoConfig;setConfig:Dispatch<SetStateAction<ResolvedVideoConfig>>;request:<T>(url:string,init?:RequestInit)=>Promise<T>};

const createTextLayer=():VideoTextLayer=>({id:globalThis.crypto?.randomUUID?.()??`text-${Date.now()}`,text:'核心区域优质资产',position:{x:540,y:340},style:{fontSize:46,color:'#ffffff',fontWeight:700}});

export const SystemSettingsPage=({config,setConfig,request}:Props)=>{
  const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');const [update,setUpdate]=useState<UpdateStatus>({running:false,log:'',version:'读取中…'});
  const refreshUpdate=()=>request<UpdateStatus>('/api/system/update/status').then(setUpdate).catch((error:Error)=>setNotice(error.message));
  useEffect(()=>{void refreshUpdate();},[]);
  useEffect(()=>{if(!update.running)return;const timer=window.setInterval(()=>void refreshUpdate(),1500);return()=>window.clearInterval(timer);},[update.running]);
  const save=async()=>{setSaving(true);setNotice('');try{const saved=await request<ResolvedVideoConfig>('/api/settings/video',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(config)});setConfig(saved);setNotice('视频默认配置已保存。');}catch(error){setNotice(error instanceof Error?error.message:'保存失败。');}finally{setSaving(false);}};
  const patchLayer=(id:string,patch:(layer:VideoTextLayer)=>VideoTextLayer)=>setConfig((current)=>({...current,textLayers:current.textLayers.map((layer)=>layer.id===id?patch(layer):layer)}));
  const startUpdate=async()=>{setNotice('');try{const result=await request<{message:string}>('/api/system/update',{method:'POST'});setNotice(result.message);setUpdate((current)=>({...current,running:true,log:'开始更新...\n'}));}catch(error){setNotice(error instanceof Error?error.message:'启动更新失败。');await refreshUpdate();}};

  return <>
    {notice&&<div className="notice" role="status">{notice}</div>}
    <section className="panel"><div className="section-heading"><div><span className="section-number">01</span><h2>视频默认配置</h2></div><button className="primary-button" type="button" disabled={saving} onClick={save}>{saving?'正在保存…':'保存默认配置'}</button></div>
      <div className="config-grid">
        <div className="config-group"><h3>字幕设置</h3><label className="toggle"><input type="checkbox" checked={config.subtitle.enabled} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,enabled:e.target.checked}}))}/> 开启字幕</label><label>默认字幕文字<textarea value={config.subtitle.text} placeholder="留空时使用语音逐句字幕" onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,text:e.target.value}}))}/></label><div className="inline-fields"><label>X 坐标<input type="number" value={config.subtitle.position.x} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,position:{...c.subtitle.position,x:Number(e.target.value)}}}))}/></label><label>Y 坐标<input type="number" value={config.subtitle.position.y} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,position:{...c.subtitle.position,y:Number(e.target.value)}}}))}/></label></div><div className="inline-fields"><label>字号<input type="number" min="12" max="120" value={config.subtitle.style.fontSize} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,style:{...c.subtitle.style,fontSize:Number(e.target.value)}}}))}/></label><label>字体颜色<input type="color" value={config.subtitle.style.color} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,style:{...c.subtitle.style,color:e.target.value}}}))}/></label><label>粗细<input type="number" min="100" max="900" step="50" value={config.subtitle.style.fontWeight} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,style:{...c.subtitle.style,fontWeight:Number(e.target.value)}}}))}/></label></div><label>背景颜色<input value={config.subtitle.style.background??''} onChange={(e)=>setConfig((c)=>({...c,subtitle:{...c.subtitle,style:{...c.subtitle.style,background:e.target.value}}}))}/></label></div>
        <div className="config-group"><h3>联系方式</h3><label className="toggle"><input type="checkbox" checked={config.contact.enabled} onChange={(e)=>setConfig((c)=>({...c,contact:{...c.contact,enabled:e.target.checked}}))}/> 在尾页显示</label><label>姓名<input value={config.contact.name??''} onChange={(e)=>setConfig((c)=>({...c,contact:{...c.contact,name:e.target.value}}))}/></label><label>微信<input value={config.contact.wechat??''} onChange={(e)=>setConfig((c)=>({...c,contact:{...c.contact,wechat:e.target.value}}))}/></label><label>电话<input value={config.contact.phone??''} onChange={(e)=>setConfig((c)=>({...c,contact:{...c.contact,phone:e.target.value}}))}/></label></div>
        <div className="config-group"><h3>Logo 配置</h3><label className="toggle"><input type="checkbox" checked={config.logo.enabled} onChange={(e)=>setConfig((c)=>({...c,logo:{...c.logo,enabled:e.target.checked}}))}/> 显示 Logo</label><label>Logo 地址<input value={config.logo.url} placeholder="brand/logo.png" onChange={(e)=>setConfig((c)=>({...c,logo:{...c.logo,url:e.target.value}}))}/></label><label>透明度：{config.logo.opacity.toFixed(2)}<input type="range" min="0" max="1" step="0.05" value={config.logo.opacity} onChange={(e)=>setConfig((c)=>({...c,logo:{...c.logo,opacity:Number(e.target.value)}}))}/></label></div>
      </div>
      <div className="layers-heading"><div><h3>自定义文字</h3><p>可添加多个宣传语、卖点或活动信息图层。</p></div><button className="secondary-button" type="button" onClick={()=>setConfig((c)=>({...c,textLayers:[...c.textLayers,createTextLayer()]}))}>新增文字图层</button></div>
      <div className="layer-list">{config.textLayers.length===0?<div className="empty-state"><span>暂未添加自定义文字</span></div>:config.textLayers.map((layer,index)=><div className="config-group layer-card" key={layer.id}><div className="layer-title"><strong>文字图层 {index+1}</strong><button type="button" onClick={()=>setConfig((c)=>({...c,textLayers:c.textLayers.filter((item)=>item.id!==layer.id)}))}>删除</button></div><label>文本内容<textarea value={layer.text} onChange={(e)=>patchLayer(layer.id,(item)=>({...item,text:e.target.value}))}/></label><div className="inline-fields"><label>X 坐标<input type="number" value={layer.position.x} onChange={(e)=>patchLayer(layer.id,(item)=>({...item,position:{...item.position,x:Number(e.target.value)}}))}/></label><label>Y 坐标<input type="number" value={layer.position.y} onChange={(e)=>patchLayer(layer.id,(item)=>({...item,position:{...item.position,y:Number(e.target.value)}}))}/></label></div><div className="inline-fields"><label>字号<input type="number" value={layer.style.fontSize} onChange={(e)=>patchLayer(layer.id,(item)=>({...item,style:{...item.style,fontSize:Number(e.target.value)}}))}/></label><label>颜色<input type="color" value={layer.style.color} onChange={(e)=>patchLayer(layer.id,(item)=>({...item,style:{...item.style,color:e.target.value}}))}/></label><label>粗细<input type="number" min="100" max="900" step="50" value={layer.style.fontWeight} onChange={(e)=>patchLayer(layer.id,(item)=>({...item,style:{...item.style,fontWeight:Number(e.target.value)}}))}/></label></div></div>)}</div>
    </section>
    <section className="panel"><div className="section-heading"><div><span className="section-number">02</span><h2>系统更新</h2><p>当前版本：{update.version}</p></div><div className="button-row"><button className="secondary-button" type="button" onClick={()=>void refreshUpdate()}>检查更新</button><button className="primary-button" type="button" disabled={update.running} onClick={()=>void startUpdate()}>{update.running?'正在更新…':'立即更新'}</button></div></div><pre className="update-log" aria-live="polite">{update.log||'尚未执行更新。'}</pre></section>
  </>;
};
